@startuml DWM1001Transform
!theme vibrant
skinparam dpi 100
skinparam DefaultFontName Arial
left to right direction

queue "input/tag_position" as input_tag 
queue "  tf  " as tf_topic
queue "tf_static" as tf_static_topic
queue "output/odometry/ips" as output_odom_ips
node TransformNode 
input_tag --> TransformNode : "geometry_msgs/PointStamped"
tf_topic --> TransformNode : "tf2_msgs/TFMessage"
tf_static_topic --> TransformNode : "tf2_msgs/TFMessage"
TransformNode --> output_odom_ips : "nav_msgs/Odometry"
 
@enduml